### ISSUE TITLE
FR: Make sidebar more space efficient

### ISSUE THREAD

**Issue by chrisgrieser** [anoopkcn/obsidian-reference-map#2]
Thank you for the plugin, it seems incredibly useful!

Given the nature of the plugin, there is often a lot of content added in its sidebar tab, not only requiring you to scroll through it, but even requiring you to scroll a lot sometimes.

Therefore, I think it might make sense to make this the sidebar more space efficient, for example by removing padding and reducing font size.

Also, here are some ui changes which could save even more space:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/73286100/210333310-75ec397d-d95c-4944-8bf8-8b136291d852.png">

**Comment by anoopkcn** [comment]
Hi @chrisgrieser, Thanks for your excellent suggestions.  Show buttons on hover and showing only the year instead of the date will be excellent; I will add them to the plugin. But I must consider how to style the citing/cited section heading. If you have suggestions, It would be great. Also, I will add a search functionality so that one does not have to scroll that much in certain situations.

**Comment by anoopkcn** [comment]
Hi, I made the changes you suggested. Please check version [0.4.1](https://github.com/anoopkcn/obsidian-reference-map/releases/tag/0.4.1). 
You can enable show/hide buttons on hover at the plugin's settings page. 

<img width="291" alt="reference-map-view" src="https://user-images.githubusercontent.com/14111873/210580133-a64e21a6-6cc0-427d-bfd3-f3a16a2f2fe6.png">

**Comment by chrisgrieser** [comment]
thanks 🥳
