### ISSUE TITLE
Issue fetching references

### ISSUE THREAD

**Issue by pcuellar** [anoopkcn/obsidian-reference-map#25]
**Describe the bug**

Starting today, I started getting an error when retrieving references. Nothing shows up on the panel even though there are several references on the active note.

**To Reproduce**

Open a note with @citekeys, nothing happens on the plugin board 

**Console output**

![s1](https://user-images.githubusercontent.com/20482146/222181350-8d433713-a866-49e9-87e7-5d1f9e4114f4.jpeg)

**Expected behavior**

References showing on the plugin panel

**Platform**

-   OS: Ventura 13.2.1
-   Obsidian version: 1.1.15
-   Plugin version: 1.2.3

**Comment by anoopkcn** [comment]
I can't reproduce the issue can you send me the markdown file and  `csl-json` file or the  `bib` file you are using for the citekey?

**Comment by pcuellar** [comment]
I re-exported my Zotero library as both `csl-json` and as `bib` (via Better BibTex) and the error went away. However, the plugin keeps telling me there are "no valid references found". Here is a note and my .json file.

[Archive.zip](https://github.com/anoopkcn/obsidian-reference-map/files/10873062/Archive.zip)

**Comment by pcuellar** [comment]
I re-exported my library and the issue went away. Thanks!

**Comment by anoopkcn** [comment]
`@medinaImportedMagicEssays2014` citekey doesnt seem to have a DOI  associated with it

**Comment by pcuellar** [comment]
yeah, I was confused and thought that the plugin will pick up data **only** from a citekey even if a DOI was not present. When I tested with a note that had both pieces after re-exporting the library it worked.

**Comment by anoopkcn** [comment]
Yea, at the momement the DOI has to   be present there is  an option to get  references using other  kinds of metadata like `title` but I disabled this feature in the  production version because it gives incoinsistant results, because it does a universal search  and returns the closest match (so it might not be the paper you  are loking for).

long way to say, you  have to have a DOI or  a static ID in the DOI  field to get the reference associated  with a citekey.
