### ISSUE TITLE
Detect citekeys / pandoc citations followed by page numbers

### ISSUE THREAD

**Issue by FeralFlora** [anoopkcn/obsidian-reference-map#26]
**Is your feature request related to a problem? Please describe.**
The problem is that Reference Map does not detect pandoc citations with citekeys followed by a page number.

Example:
This is recognized `[@Psillos1996ScientificRealismPessimistic]` but not `[@Psillos1996ScientificRealismPessimistic, p. 313]`.

**Describe the solution you'd like**
Since it is common to cite a specific page from a citation, it would be very useful (indeed essential, in my usecase) if Reference Map was able to detect citekeys that are followed by page numbers like so [@citekey, p. x].

**Describe alternatives you've considered**
The Pandoc Reference List plugin is capable of detecting citekeys despite page numbers without issue, so it should be doable, perhaps by borrowing some code from there.

**Comment by anoopkcn** [comment]
Hi, the `comma` is regarded as a citekey character by the reference map( the` spaces`, `[`, `(` or `*` are  the characters that are not regarded as part of the citation key). This was decided because people also use `,` as a field separation character. In your case  `[@Psillos1996ScientificRealismPessimistic , p. 313]` will detect the citation key(notice the space after the  citation key). But I can see how it is not an ideal solution. In the future version of Reference Map, I  will add a setting for assigning characters that are not part of the citation key.

**Comment by MSBack** [comment]
>In the future version of Reference Map, I will add a setting for assigning characters that are not part of the citation key.

I hope you do, because the suggested workaround is not viable, because the space will stay after exporting using Pandoc, which is a formatting issue.

**Comment by anoopkcn** [comment]
Hi @FeralFlora I fixed this issue. You will now have an additional settings option for defining any characters that are not part of the citekey (Defauly: ,) 
<img width="780" alt="filter chars" src="https://github.com/anoopkcn/obsidian-reference-map/assets/14111873/f718a478-8ae9-42d1-996d-592aa5037bbc">
Please check the implementation(Sorry for the delay)
