### ISSUE TITLE
Filter redundent references

### ISSUE THREAD

**Issue by M4THG33K2018** [anoopkcn/obsidian-reference-map#31]
When the plugin searches for papers using semantic scholar, their database often seems inaccurate. an example is:
"AstronomicAL An interactive dashboard for visualisation integration and classification of data using Active Learning - G Stevens 2021"  - the original paper references 17 items, Semantic Scholar references 29, some are obviously bugs on their end.
Top             |  bottom
:-------------------------:|:-------------------------:
![image](https://github.com/anoopkcn/obsidian-reference-map/assets/41141396/d5ac0164-96e2-46de-98fc-fe9d775a1cbf) |![image](https://github.com/anoopkcn/obsidian-reference-map/assets/41141396/e1d88ef0-cfe3-4781-8bf9-aea8863b303d)

Above demonstrates the issue

[Semantic Scholar link](https://www.semanticscholar.org/paper/AstronomicAL%3A-An-interactive-dashboard-for-and-of-Stevens-Fotopoulou/85087ba46b6b1e9a50add4aa762b8ae66610aa66)

Appreciate you can't change Semantic Scholars side - Since broken links do not exist on Semantic Scholar, they have zero citations and zero references. Could you provide an option to filter these out from Batch results?

**Comment by anoopkcn** [comment]
Hi @M4THG33K2018, Thanks for the suggestion. This issue is fixed in the latest version of the plugin. Now you have a new settings option where you can turn ON the `Hide or Show Redundant References` option(default OFF). All citations and references with zero cited and zero citing entries will be hidden from the list. 

PS: I just noticed a spelling mistake in the Option heading but I will fix that in the next patch version :)
