### ISSUE TITLE
Use Zotero Library as Semantic Scholar Fallback

### ISSUE THREAD

**Issue by braeden-muller** [anoopkcn/obsidian-reference-map#32]
Sometimes when using the application I reference a work not published as a traditional academic text, but are still meaningful to me (e.g. university lecture slides, internal company training, presentation, non-academic book, etc.). These are not counted as references by the plugin, yet they have entries and data in my Zotero library.

The feature I am proposing would be using the exported json or bib from a Zotero library as a fallback option if nothing is found on Semantic Scholar. Even if certain metrics are unavailable, such as cited works and citations, other information such as title, author, abstract, and BibTeX are still available. When using Zotero as a fallback, unavailable information is greyed out, but the reference is still counted as a reference and accessible via the reference map.

**Comment by amzon-ex** [comment]
Came here to make this request and I'm glad to see I found the exact same one! It would be great to have this feature. It also turns out that Semantic Scholar does not enlist some famous books/articles as well - which are in turn available in Google Scholar, but I'm aware of the API limitations of Google Scholar. So, adding fallback to the bibtex/json file would still be useful.

**Comment by FeralFlora** [comment]
@braeden-muller @amzon-ex Isn't this already possible? See https://github.com/anoopkcn/obsidian-reference-map/wiki/integrating-with-zotero-or-bibdesk

**Comment by anoopkcn** [comment]
Hi @braeden-muller @amzon-ex @FeralFlora 
The latest release version of the plugin includes Zotero as a fallback library(i.e if the entry is not found online). In addition to this, now you can also cite anything in the Zotero library(ex: papers, books, notes,videos, X formally known as twitter, webpages, et,.. anything that Zotero supports)

**Comment by FeralFlora** [comment]
> In addition to this, now you can also cite anything in the Zotero library(ex: papers, books, notes,videos, X formally known as twitter, webpages, et,.. anything that Zotero supports)

Wait, so Reference map can insert citations now?

**Comment by anoopkcn** [comment]
Hi @FeralFlora , There is a {{bibtex}} variable you can bind a button to. Is that what you are referring? 

> Also, I noticed that the results seem limited to the main library.

If you pull from zotero you can select more than one library.

<img width="794" alt="Screenshot 2023-11-25 at 23 37 14" src="https://github.com/anoopkcn/obsidian-reference-map/assets/14111873/c2521d5d-6b32-43ef-ba49-ea4e5d3eb904">

**Comment by FeralFlora** [comment]
> Hi @FeralFlora , There is a {{bibtex}} variable you can bind a button to. Is that what you are referring?
Hi @anoopkcn,

No, not exactly, but that's useful to know. I meant when you use the following command:
![image](https://github.com/anoopkcn/obsidian-reference-map/assets/33608083/5ce67701-0364-45ae-bb1d-9b75d073b1ed)
I was expecting it to give a citekey citation like: `[@Bell.etal2019SpatialHabitatVariation]`.

This is what you need for academic workflows from markdown to publication using Pandoc. It would be nice to have such citations as an option (pulling from Zotero), either through the command palette or (preferably) through autocompletion.

I case you aren't aware, your "competitor" is [Pandoc Reference List](https://github.com/mgmeyers/obsidian-pandoc-reference-list), which does some of what Reference Map does, but also some other things like citekey autocompletion, citekey citation rendering as formatted citations and such. Of course, Reference Map also has distinct features for literature reviews and mapping. Since both plugins overlap, but also extend past each other in different directions, I am torn.

> If you pull from zotero you can select more than one library.

Oh, right, I forgot about that setting.

**Comment by anoopkcn** [comment]
> This is what you need for academic workflows from markdown to publication using Pandoc. It would be nice to have such citations as an option (pulling from Zotero), either through the command palette or (preferably) through autocompletion.

Regarding completion:  I usually use Zotlit autocompletion OR the wonderful Alfred `Supercharged Citation Picker` by @chrisgrieser(it gives me a bit more control, like inserting page numbers, multiple citations and so on), Although it would be nice to have something like that in Reference Map. 

Pandoc Citation styles: I have a working version; you can expect this in the next minor release version. Hopefully, version 1.6.0. The way it would work is a new variable will be available called {{pandoc}} where you can bind it to a button in the reference map. Before I can release it, I have to add an option to show pandoc-styled citations in the index cards,  configurations for citation styles, and global copy(copy all citations at once), so it is a work in progress atm :) 

> citekey citation rendering as formatted citations and such
This is also something I am planning to do but dont have an implementation at the moment.

**Comment by amzon-ex** [comment]
Thanks for the regular improvements to this plugin, @anoopkcn !

I have used Pandoc Reference List before and as useful as it is, I moved away from it because you need an additional pandoc installation to use it (hence the name). I like that your plugin has no dependencies, even though the output is not always properly formatted. Support for citation styles would be great, however!

**Comment by FeralFlora** [comment]
> Thanks for the regular improvements to this plugin, @anoopkcn !
> 
> I have used Pandoc Reference List before and as useful as it is, I moved away from it because you need an additional pandoc installation to use it (hence the name). I like that your plugin has no dependencies, even though the output is not always properly formatted. Support for citation styles would be great, however!

I don't really see that as a downside of Pandoc Reference List (or if it became a dependency of Reference Map), because Pandoc is a must-have for markdown-based academic workflows, in my opinion. Of course, there could be exceptions, but I reckon they are few. To backtrack slightly, I do think it's a downside for mobile workflows, since using Pandoc there is not very feasible, from what I've seen. Then again, Reference Map is already desktop only.

**Comment by FeralFlora** [comment]
> Regarding completion: I usually use Zotlit autocompletion OR the wonderful Alfred `Supercharged Citation Picker` by @chrisgrieser(it gives me a bit more control, like inserting page numbers, multiple citations and so on), Although it would be nice to have something like that in Reference Map.

I am using Zotero Integration for literature notes, Pandoc Reference List for citation autocompletion on desktop, this [custom dictionary](https://forum.obsidian.md/t/mobile-citation-autocompletion-guide-using-quickadd-and-various-complements/63099/15) for [Various complements](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) for mobile autocompletion, and recently, an annotation search and picker I made using Templater & Dataview for references to specific annotations / page numbers:

https://github.com/anoopkcn/obsidian-reference-map/assets/33608083/b68b6e09-aaeb-4390-a7d6-58161cf8b664

I don't have a Mac, so I don't have access to the Supercharged Citation Picker.

Glad to hear that you are working on Pandoc citations, and citation rendering. That's awesome! Like @amzon-ex, thanks for all the work you are putting into this.

> EDIT: btw, I also use Pandoc Reference List. It is an excellent plugin. However, I can understand the reluctance to use 2 plugins that do some things the same. In my mind, Reference Map is more like a reference exploration plugin :)

Yeah, I see it that way too! But with those features you mentioned you are implementing, the only read difference will be the citation autocompletion (which, to be fair, is perhaps a bit misplaced in Pandoc Reference List—but very nice nonetheless).

**Comment by anoopkcn** [comment]
Hi @FeralFlora 

> and recently, an annotation search and picker I made using Templater & Dataview for references to specific annotations / page numbers:

This looks super cool 👌.  Picking individual annotations is very useful. I saw the post on discord, I will try this out, Thanks
